version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/assets/"
    schedule:
      interval: "daily"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Berlin"
    assignees:
      - "heinrichreimer"
    reviewers:
      - "heinrichreimer"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Berlin"
    assignees:
      - "heinrichreimer"
    reviewers:
      - "heinrichreimer"
